### ISSUE TITLE
Missing Trained Agents Zip

### ISSUE THREAD

**Issue by thushanp** [RLMA2019/RLMA#1]
Hi!

In attempting to read through and run the code from the Minimalistic Attacks paper, it appears that the trained_agents.zip file is empty - which means that the code no longer runs.

The following command:
python PPO2_Minimalistic_Attack.py   -g   'Breakout'  -a   'ppo2'  -n   5   -t   0.9   -r   'ppo2run'

Results in the following error:
ValueError: Error: the file trained_agents/'a2c'/'Pong'NoFrameskip-v4 could not be found

Would it be possible to re-commit and push the zip folder?

Thank you!

**Comment by RLMA2019** [comment]
The pkl files for the well-trained policies have been uploaded.
